name: Take screenshot
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]
    branches: [main]

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Generate Web site screenshot
        uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          mode: page
          url: https://lauta-dev.github.io/portafolio/
      

      - name: Set up Git
        run: |
          git config  user.name "${{ secrets.GH_USERNAME }}"
          git config  user.email "${{ secrets.GH_MAIL }}"
      
      - name: Create screenshot image
        run: |
          git add .
          git commit -m "Agregar captura de pantalla"

      - name: Guardar captura
        run: |
          git push 
