name: Take screenshot
on:
  push:
    branches:
      - main

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: webpage-screenshot
        uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: https://google.com
      
      - name: Guardar captura
        run: |
          git config --local user.name {{ secrets.GH_USERNAME }}
          git config --local user.email {{ secrets.GH_MAIL }}
          git add .
          git commit -m "Agregar captura de pantalla"
          git push
