name: Take screenshot
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]
    branches: [main]

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Generar imgenes
        uses: lauta-dev/website-screenshot-capture-action@v1.0.7
        with:
          pages_file: pages.yml

      - name: Subir artefacto
        uses: actions/upload-artifact@v3
        with:
          name: todas-las-imagenes
          path: screenshots/

  optimize-images:
    runs-on: ubuntu-latest
    needs: [screenshots]
    steps:
      - name: instalando ImageMagick
        run: sudo apt-get install -y webp

      - name: Descargar artefacto
        uses: actions/download-artifact@v3
        with:
          name: todas-las-imagenes

      - name: Convertir de png a webp
        run: |
          for img in *.png; do
            remove_ext=$(echo $img | sed "s/.png/.webp/")
            echo "$img to $remove_ext"
            cwebp -q 50 "$img" -o "$remove_ext"
          done

      - name: Crear contener para webp
        run: mkdir webp

      - name: ls
        run: ls
      - name: Crear contener e mover las imagenes optimizadas 
        run: mv *.webp webp/

      - name: Subir artefacto
        uses: actions/upload-artifact@v3
        with:
          name: todas-las-imagenes-webp
          path: webp/

  push-images:
    runs-on: ubuntu-latest
    needs: [optimize-images]
    steps:
      - name: Clonar repo de recursos
        run: git clone https://github.com/Lauta-dev/resource.git .

      - name: Descargar artefacto
        uses: actions/download-artifact@v3
        with:
          name: todas-las-imagenes

      - name: ls webp
        run: ls 
      
      - name: Set up Git
        run: |
          git config user.name "${{ secrets.GH_USERNAME }}"
          git config user.email "${{ secrets.GH_MAIL }}"
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/Lauta-dev/resource.git
      
      - name: Create screenshot image
        run: |
          git add .
          git commit -m "Agregar captura de pantalla"
      
      - name: Guardar captura
        run: |
          git push origin main
