name: Take screenshot
on:
  push:
    branches:
      - main

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: webpage-screenshot
        uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: https://google.com
      
      - name: ls
        uses: ls
