name: Take screenshot
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]
    branches: [main]

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Generara captura de pantalla del porfolio
        uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          mode: page
          url: https://lauta-dev.github.io/portafolio/
          output: porfolio.png
      
      - name: Generar captura de pantalla de lauta-dev/csv-viewer
        uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          mode: page
          url: https://csv-viewer-eight.vercel.app/
          output: csv-viewer.png

      - name: Generar captura de pantalla de lauta-dev/short-url
        uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          mode: page
          url: https://short-url-clien.vercel.app/
          output: short-url.png

      - name: Crear contenedor
        run: mkdir images

      - name: mover a contenedor
        run: mv *.png images

      - name: Subir artefacto
        uses: actions/upload-artifact@v3
        with:
          name: todas-las-imagenes
          path: images/

  optimize-images:
    runs-on: ubuntu-latest
    needs: [screenshots]
    steps:
      - name: instalando ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Descargar artefacto
        uses: actions/download-artifact@v3
        with:
          name: todas-las-imagenes

      - name: Convertir de png a webp
        run: |
          for img in *.png; do
            convert "$img" "${img%.png}.webp"
            echo "$img"
          done

      - name: Crear contener para webp
        run: mkdir webp

      - name: ls
        run: ls
      - name: Crear contener e mover las imagenes optimizadas 
        run: mv *.webp webp/

      - name: Subir artefacto
        uses: actions/upload-artifact@v3
        with:
          name: todas-las-imagenes-webp
          path: webp/

  push-images:
    runs-on: ubuntu-latest
    needs: [optimize-images]
    steps:
      - name: Clonar repo de recursos
        run: git clone https://github.com/Lauta-dev/resource.git .

      - name: Descargar artefacto
        uses: actions/download-artifact@v3
        with:
          name: todas-las-imagenes

      - name: ls webp
        run: ls 
      
      - name: Set up Git
        run: |
          git config user.name "${{ secrets.GH_USERNAME }}"
          git config user.email "${{ secrets.GH_MAIL }}"
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/Lauta-dev/resource.git
      
      - name: Create screenshot image
        run: |
          git add .
          git commit -m "Agregar captura de pantalla"
      
      - name: Guardar captura
        run: |
          git push origin main
