name: Take screenshot
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]
    branches: [main]

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2


      - name: Generar imgenes
        uses: lauta-dev/website-screenshot-capture-action@main
        with:
          ulrs_input_file: pages.yml
          type: webp
          quality: 75
          output_dir: dir

      - name: Subir artefacto
        uses: actions/upload-artifact@v3
        with:
          name: todas-las-imagenes
          path: dir/

  push-images:
    runs-on: ubuntu-latest
    needs: [screenshots]
    steps:
      - name: Clonar repo de recursos
        run: git clone https://github.com/Lauta-dev/resource.git .

      - name: Descargar artefacto
        uses: actions/download-artifact@v3
        with:
          name: todas-las-imagenes

      - name: Set up Git
        run: |
          git config user.name "${{ secrets.GH_USERNAME }}"
          git config user.email "${{ secrets.GH_MAIL }}"
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/Lauta-dev/resource.git
      
      - name: Create screenshot image
        run: |
          git add .
          git commit -m "Agregar captura de pantalla"
      
      - name: Guardar captura
        run: |
          git push origin main
