name: Take screenshot
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]
    branches: [main]

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo de recursos
        run: git clone https://github.com/Lauta-dev/resource.git .
      
      - name: Generate Web site screenshot
        uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          mode: page
          url: https://lauta-dev.github.io/portafolio/
          output: porfolio.png

      - name: ls
        run: ls

      - name: Set up Git
        env:
          TOKEN: ${{  secrets.ACCCESS_TOKEN }}
        run: |
          git config  user.name "${{ secrets.GH_USERNAME }}"
          git config  user.email "${{ secrets.GH_MAIL }}"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/Lauta-dev/resource.git
      
      - name: Create screenshot image
        run: |
          git add .
          git commit -m "Agregar captura de pantalla"

      
      - name: Guardar captura
        run: |
          git push origin main
