# .github/workflows/trigger-base-repo-action.yml en repos "a", "b", "c"
name: Trigger Base Repo Action on Push

on:
  push:
    branches:
      - main 

jobs:
  trigger-repo-base:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger action in base repo
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Lauta-dev/resource/dispatches \
            -d '{"event_type":"on","client_payload":{"unit":false,"integration":true}}'


