# .github/workflows/trigger-base-repo-action.yml en repos "a", "b", "c"
name: Trigger Base Repo Action on Push

on:
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  trigger-repo-base:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger action in base repo
        run: |
          curl -X POST https://api.github.com/repos/lauta-dev/resource/repository_dispatch \
          -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
          -d '{"event_type": "push-event"}'

